# Role Configuration - Development Environment
environment: DEV

roles:
  - name: Read Access
    members:
      - "WINTRUST\\DM-BAR-Reporting"
      - "WINTRUST\\DM_PBI_ProgMgmt"
      - "WINTRUST\\BU_Wealth_GLA_PortfolioManagers"
      - "WINTRUST\\DM_DWBI"
      - "WINTRUST\\DM_SSRS_PBI_TFS_ReleaseManager"
      - "WINTRUST\\BU_Wealth_DEV"
      - "WINTRUST\\TEMP_BU_Wealth_WTI_FinancialAdvisors"
      - "WINTRUST\\DM_DG_Reporting"
  - name: Read_Process Access
    members:
      - "WINTRUST\\DB_BAR_SVC_PROD_SSASReadProcess"
      - "WINTRUST\\SVC_DM_ETL_UAT"
      - "WINTRUST\\SVC_DM_ETL_DEV"
  - name: CTC
    members:
      - "WINTRUST\\SG-WT-ENT-PRD-PBI-U-BU-WEALTH-CTC-SUPERUSERS"
  - name: WTI
    members:
      - "WINTRUST\\BU_Wealth_WTI_SuperUsers"
  - name: GLA
    members:
      - "WINTRUST\\BU_Wealth_GLA_SuperUsers"

